server:
  port: 6080
  servlet:
    context-path: /onboarding


spring:
  #JPA Config
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres


#onboarding database
io.excitingstartup.onboarding.datasource.onboarding:
 url: jdbc:postgresql://localhost:5432/onboarding?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=yes&characterEncoding=UTF-8
 username: postgres
 password : root123
 driverClassName : org.postgresql.Driver


#shard database
io.excitingstartup.onboarding.datasource.sharddb:
 url: jdbc:postgresql://localhost:5432/sharddb?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=yes&characterEncoding=UTF-8
 username: postgres
 password : root123
 driverClassName : org.postgresql.Driver


logging:
  level:
    root: DEBUG



